default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres # Укажите пользователя PostgreSQL
  password: 1234 # Укажите пароль без угловых скобок
  host: localhost # Или IP сервера PostgreSQL

development:
  <<: *default
  database: Travel_development

test:
  <<: *default
  database: Travel_test

production:
  <<: *default
  database: Travel_production
  username: postgres 
  password: 1234 